In [1]:
import pandas as pd

In [10]:
X_train = pd.read_csv('IMDb_train.csv')
X_test = pd.read_csv('IMDb_test.csv')
y_train = pd.read_csv('y_train.csv')
y_test = pd.read_csv('y_test.csv')

In [11]:
print(X_train.shape[0], 'Rijen')
print(X_train.shape[1], 'Kolommen')
X_train.head()

404 Rijen
13 Kolommen

,label,collections,title,genre,director,writer,stars,IMDb rating,IMDb description,air date,duration,content rating,url
0,Soldiers_of_the_Empire_st_dsn.txt,Collection: tvseries: Star Trek: Deep Space Nine,"""Star Trek: Deep Space Nine"" Soldiers of the E...","['Action', 'Adventure', 'Drama']",['LeVar Burton'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Michael ...",7.6,Dax and Worf accompany Martok on his first com...,1997-04-28,PT47M,TV-PG,https://www.imdb.com/title/tt0708603
1,Cold_Fire_st_v.txt,Collection: tvseries: Star Trek: Voyager,"""Star Trek: Voyager"" Cold Fire (TV Episode 199...","['Action', 'Adventure', 'Drama']",['Cliff Bole'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Kate Mulgrew', 'Robert Beltran', 'Roxann Daw...",7.0,"The Caretaker&apos;s remains resonate, which m...",1995-11-13,PT46M,TV-PG,https://www.imdb.com/title/tt0708866
2,Armageddon_Game_st_dsn.txt,Collection: tvseries: Star Trek: Deep Space Nine,"""Star Trek: Deep Space Nine"" Armageddon Game (...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Rick Berman', 'Michael P...","['Avery Brooks', 'Rene Auberjonois', 'Alexande...",7.4,"Chief O&apos;Brien, who still doesn&apos;t par...",1996-04-12,PT46M,TV-PG,https://www.imdb.com/title/tt0708500
3,All_Good_Things_st_ng.txt,Collection: tvseries: Star Trek: The Next Gene...,"""Star Trek: The Next Generation"" All Good Thin...","['Action', 'Adventure', 'Drama']",['Winrich Kolbe'],"['Gene Roddenberry', 'Ronald D. Moore', 'Brann...","['Patrick Stewart', 'Jonathan Frakes', 'LeVar ...",9.1,Capt. Picard finds himself shifting continuall...,1994-05-23,PT1H45M,TV-PG,https://www.imdb.com/title/tt0111281
4,A_Hundred_Yards_Over_the_Rim_tz.txt,Collection: tvseries: The Twilight Zone (1959),"""The Twilight Zone"" A Hundred Yards Over the R...","['Drama', 'Fantasy', 'Horror']",['Buzz Kulik'],['Rod Serling'],"['Cliff Robertson', 'John Crawford', 'Evans Ev...",8.1,The leader of a wagon train across the New Mex...,1961-04-07,PT25M,TV-PG,https://www.imdb.com/title/tt0734541/

In [14]:
print(y_train.shape[0], 'Rijen')
print(y_train.shape[1], 'Kolommen')
y_train.head()

404 Rijen
10 Kolommen

,alien point of view,belonging,father and son,friendship,human vs. captivity,husband and wife,infatuation,obsession,romantic love,time travel
0,1,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,1,0
3,1,0,0,1,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,1

In [13]:
complete = X_train.concatenate(y_train)

AttributeError: 'DataFrame' object has no attribute 'concatenate'